export default [
    {
        type: 'independent',
        capacity: 20,
        items: [
            {
                group: '1',
                weight: 1,
                value: 1,
            },
            {
                group: '2',
                weight: 1,
                value: 1,
            },
            {
                group: '3',
                weight: 1,
                value: 1,
            },
            {
                group: '4',
                weight: 10,
                value: 10,
            },
            {
                group: '5',
                weight: 5,
                value: 60,
            },
            {
                group: '6',
                weight: 4,
                value: 4,
            },
            {
                group: '7',
                weight: 4,
                value: 4,
            },
            {
                group: '8',
                weight: 4,
                value: 4,
            },
            {
                group: '9',
                weight: 4,
                value: 4,
            },
        ],
        expectedValues: [60, 1, 1, 1, 4, 4, 4],
        optimalValue: 75,
    },
    {
        type: 'independent',
        capacity: 6,
        items: [
            {
                group: '1',
                weight: 6,
                value: 4.4,
            },
            {
                group: '2',
                weight: 10,
                value: 5.6,
            },
        ],
        expectedValues: [4.4],
        optimalValue: 4.4,
    },
    {
        type: 'independent',
        capacity: 6,
        items: [
            {
                group: '1',
                weight: 6,
                value: 4.4,
            },
            {
                group: '2',
                weight: 5,
                value: 5.6,
            },
        ],
        expectedValues: [5.6],
        optimalValue: 5.6,
    },
    {
        type: 'independent',
        capacity: 6,
        items: [
            {
                group: '1',
                weight: 4,
                value: 4.4,
            },
            {
                group: '2',
                weight: 5,
                value: 5.6,
            },
        ],
        expectedValues: [5.6],
        optimalValue: 5.6,
    },
    {
        type: 'independent',
        capacity: 5,
        items: [
            {
                group: '1',
                weight: 2,
                value: 100,
            },
        ],
        expectedValues: [100],
        optimalValue: 100,
    },
    {
        type: 'independent',
        capacity: 1,
        items: [
            {
                group: '1',
                weight: 2,
                value: 100,
            },
        ],
        expectedValues: [],
        optimalValue: 0,
    },
    {
        type: 'independent',
        capacity: 1,
        items: [
            {
                group: '1',
                weight: 1,
                value: 100,
            },
        ],
        expectedValues: [100],
        optimalValue: 100,
    },
    {
        type: 'independent',
        capacity: 0,
        items: [],
        expectedValues: [],
        optimalValue: 0,
    },
    {
        type: 'independent',
        capacity: 10,
        items: [
            {
                group: '1',
                weight: 1.98,
                value: 100,
            },
            {
                group: '2',
                weight: 3.14,
                value: 50,
            },
            {
                group: '3',
                weight: 2,
                value: 40,
            },
            {
                group: '4',
                weight: 5,
                value: 95,
            },
            {
                group: '5',
                weight: 3,
                value: 30,
            },
        ],
        expectedValues: [100, 40, 95],
        optimalValue: 235,
    },
    {
        type: 'independent',
        capacity: 10,
        items: [
            {
                group: '1',
                weight: 1.98,
                value: 100,
            },
            {
                group: '2',
                weight: 3.14,
                value: 50,
            },
            {
                group: '3',
                weight: 2,
                value: 40,
            },
            {
                group: '4',
                weight: 5,
                value: 95,
            },
            {
                group: '5',
                weight: 3,
                value: 30,
            },
        ],
        expectedValues: [100, 40, 95],
        optimalValue: 235,
    },
    {
        type: 'independent',
        expectedValues: [
            115,
            230,
            230,
            140,
            280,
            154,
            154,
            163,
            326,
            652,
            163,
            209,
            418,
            836,
            237,
            474,
            948,
            711,
            241,
            482,
            482,
            290,
            314,
            628,
            1256,
            314,
            314,
            628,
            628,
            324,
            648,
            648,
            335,
            670,
            1340,
            335,
            346,
            692,
            1384,
            347,
            694,
            1388,
            694,
            356,
            712,
            1424,
            385,
            770,
            406,
            812,
            406,
            416,
            832,
            438,
            438,
            440,
            880,
            1760,
            1320,
            447,
            894,
            460,
            920,
            1840,
            477,
            479,
            958,
            958,
            521,
            1042,
            521,
            523,
            1046,
            538,
            1076,
            541,
            1082,
            1623,
            546,
            555,
            1110,
            2220,
            559,
            1118,
            1677,
            570,
            1140,
            1710,
            574,
            1148,
            2296,
            574,
            582,
            590,
            1180,
            1180,
            592,
            592,
            603,
            1206,
            2412,
            612,
            612,
            626,
            1252,
            1252,
            627,
            1254,
            632,
            1264,
            1896,
            652,
            661,
            1322,
            2644,
            661,
            677,
            1354,
            682,
            1364,
            682,
            685,
            697,
            1394,
            2091,
            699,
            1398,
            2097,
            708,
            1416,
            708,
            717,
            726,
            1452,
            2904,
            2178,
            730,
        ],
        optimalValue: 115663,
        items: [
            {
                group: '1',
                value: 717,
                weight: 617,
            },
            {
                group: '2',
                value: 717,
                weight: 617,
            },
            {
                group: '3',
                value: 438,
                weight: 338,
            },
            {
                group: '4',
                value: 438,
                weight: 338,
            },
            {
                group: '5',
                value: 632,
                weight: 532,
            },
            {
                group: '6',
                value: 1264,
                weight: 1064,
            },
            {
                group: '7',
                value: 1896,
                weight: 1596,
            },
            {
                group: '8',
                value: 749,
                weight: 649,
            },
            {
                group: '9',
                value: 1498,
                weight: 1298,
            },
            {
                group: '10',
                value: 2996,
                weight: 2596,
            },
            {
                group: '11',
                value: 749,
                weight: 649,
            },
            {
                group: '12',
                value: 826,
                weight: 726,
            },
            {
                group: '13',
                value: 1652,
                weight: 1452,
            },
            {
                group: '14',
                value: 3304,
                weight: 2904,
            },
            {
                group: '15',
                value: 1652,
                weight: 1452,
            },
            {
                group: '16',
                value: 739,
                weight: 639,
            },
            {
                group: '17',
                value: 523,
                weight: 423,
            },
            {
                group: '18',
                value: 1046,
                weight: 846,
            },
            {
                group: '19',
                value: 477,
                weight: 377,
            },
            {
                group: '20',
                value: 1027,
                weight: 927,
            },
            {
                group: '21',
                value: 2054,
                weight: 1854,
            },
            {
                group: '22',
                value: 1027,
                weight: 927,
            },
            {
                group: '23',
                value: 1092,
                weight: 992,
            },
            {
                group: '24',
                value: 2184,
                weight: 1984,
            },
            {
                group: '25',
                value: 4368,
                weight: 3968,
            },
            {
                group: '26',
                value: 1092,
                weight: 992,
            },
            {
                group: '27',
                value: 385,
                weight: 285,
            },
            {
                group: '28',
                value: 770,
                weight: 570,
            },
            {
                group: '29',
                value: 677,
                weight: 577,
            },
            {
                group: '30',
                value: 1354,
                weight: 1154,
            },
            {
                group: '31',
                value: 546,
                weight: 446,
            },
            {
                group: '32',
                value: 406,
                weight: 306,
            },
            {
                group: '33',
                value: 812,
                weight: 612,
            },
            {
                group: '34',
                value: 406,
                weight: 306,
            },
            {
                group: '35',
                value: 346,
                weight: 246,
            },
            {
                group: '36',
                value: 692,
                weight: 492,
            },
            {
                group: '37',
                value: 1384,
                weight: 984,
            },
            {
                group: '38',
                value: 726,
                weight: 626,
            },
            {
                group: '39',
                value: 1452,
                weight: 1252,
            },
            {
                group: '40',
                value: 2904,
                weight: 2504,
            },
            {
                group: '41',
                value: 2178,
                weight: 1878,
            },
            {
                group: '42',
                value: 699,
                weight: 599,
            },
            {
                group: '43',
                value: 1398,
                weight: 1198,
            },
            {
                group: '44',
                value: 2097,
                weight: 1797,
            },
            {
                group: '45',
                value: 682,
                weight: 582,
            },
            {
                group: '46',
                value: 1364,
                weight: 1164,
            },
            {
                group: '47',
                value: 682,
                weight: 582,
            },
            {
                group: '48',
                value: 335,
                weight: 235,
            },
            {
                group: '49',
                value: 670,
                weight: 470,
            },
            {
                group: '50',
                value: 1340,
                weight: 940,
            },
            {
                group: '51',
                value: 335,
                weight: 235,
            },
            {
                group: '52',
                value: 840,
                weight: 740,
            },
            {
                group: '53',
                value: 1680,
                weight: 1480,
            },
            {
                group: '54',
                value: 891,
                weight: 791,
            },
            {
                group: '55',
                value: 241,
                weight: 141,
            },
            {
                group: '56',
                value: 482,
                weight: 282,
            },
            {
                group: '57',
                value: 482,
                weight: 282,
            },
            {
                group: '58',
                value: 1002,
                weight: 902,
            },
            {
                group: '59',
                value: 2004,
                weight: 1804,
            },
            {
                group: '60',
                value: 4008,
                weight: 3608,
            },
            {
                group: '61',
                value: 3006,
                weight: 2706,
            },
            {
                group: '62',
                value: 592,
                weight: 492,
            },
            {
                group: '63',
                value: 592,
                weight: 492,
            },
            {
                group: '64',
                value: 538,
                weight: 438,
            },
            {
                group: '65',
                value: 1076,
                weight: 876,
            },
            {
                group: '66',
                value: 314,
                weight: 214,
            },
            {
                group: '67',
                value: 628,
                weight: 428,
            },
            {
                group: '68',
                value: 1256,
                weight: 856,
            },
            {
                group: '69',
                value: 314,
                weight: 214,
            },
            {
                group: '70',
                value: 440,
                weight: 340,
            },
            {
                group: '71',
                value: 880,
                weight: 680,
            },
            {
                group: '72',
                value: 1760,
                weight: 1360,
            },
            {
                group: '73',
                value: 1320,
                weight: 1020,
            },
            {
                group: '74',
                value: 913,
                weight: 813,
            },
            {
                group: '75',
                value: 1826,
                weight: 1626,
            },
            {
                group: '76',
                value: 3652,
                weight: 3252,
            },
            {
                group: '77',
                value: 163,
                weight: 63,
            },
            {
                group: '78',
                value: 326,
                weight: 126,
            },
            {
                group: '79',
                value: 652,
                weight: 252,
            },
            {
                group: '80',
                value: 163,
                weight: 63,
            },
            {
                group: '81',
                value: 745,
                weight: 645,
            },
            {
                group: '82',
                value: 1490,
                weight: 1290,
            },
            {
                group: '83',
                value: 745,
                weight: 645,
            },
            {
                group: '84',
                value: 447,
                weight: 347,
            },
            {
                group: '85',
                value: 894,
                weight: 694,
            },
            {
                group: '86',
                value: 541,
                weight: 441,
            },
            {
                group: '87',
                value: 1082,
                weight: 882,
            },
            {
                group: '88',
                value: 1623,
                weight: 1323,
            },
            {
                group: '89',
                value: 209,
                weight: 109,
            },
            {
                group: '90',
                value: 418,
                weight: 218,
            },
            {
                group: '91',
                value: 836,
                weight: 436,
            },
            {
                group: '92',
                value: 627,
                weight: 327,
            },
            {
                group: '93',
                value: 1079,
                weight: 979,
            },
            {
                group: '94',
                value: 2158,
                weight: 1958,
            },
            {
                group: '95',
                value: 290,
                weight: 190,
            },
            {
                group: '96',
                value: 627,
                weight: 527,
            },
            {
                group: '97',
                value: 1254,
                weight: 1054,
            },
            {
                group: '98',
                value: 314,
                weight: 214,
            },
            {
                group: '99',
                value: 628,
                weight: 428,
            },
            {
                group: '100',
                value: 628,
                weight: 428,
            },
            {
                group: '101',
                value: 854,
                weight: 754,
            },
            {
                group: '102',
                value: 1708,
                weight: 1508,
            },
            {
                group: '103',
                value: 3416,
                weight: 3016,
            },
            {
                group: '104',
                value: 1708,
                weight: 1508,
            },
            {
                group: '105',
                value: 570,
                weight: 470,
            },
            {
                group: '106',
                value: 1140,
                weight: 940,
            },
            {
                group: '107',
                value: 1710,
                weight: 1410,
            },
            {
                group: '108',
                value: 416,
                weight: 316,
            },
            {
                group: '109',
                value: 832,
                weight: 632,
            },
            {
                group: '110',
                value: 661,
                weight: 561,
            },
            {
                group: '111',
                value: 1322,
                weight: 1122,
            },
            {
                group: '112',
                value: 2644,
                weight: 2244,
            },
            {
                group: '113',
                value: 661,
                weight: 561,
            },
            {
                group: '114',
                value: 603,
                weight: 503,
            },
            {
                group: '115',
                value: 1206,
                weight: 1006,
            },
            {
                group: '116',
                value: 2412,
                weight: 2012,
            },
            {
                group: '117',
                value: 460,
                weight: 360,
            },
            {
                group: '118',
                value: 920,
                weight: 720,
            },
            {
                group: '119',
                value: 1840,
                weight: 1440,
            },
            {
                group: '120',
                value: 479,
                weight: 379,
            },
            {
                group: '121',
                value: 958,
                weight: 758,
            },
            {
                group: '122',
                value: 958,
                weight: 758,
            },
            {
                group: '123',
                value: 789,
                weight: 689,
            },
            {
                group: '124',
                value: 1578,
                weight: 1378,
            },
            {
                group: '125',
                value: 2367,
                weight: 2067,
            },
            {
                group: '126',
                value: 356,
                weight: 256,
            },
            {
                group: '127',
                value: 712,
                weight: 512,
            },
            {
                group: '128',
                value: 1424,
                weight: 1024,
            },
            {
                group: '129',
                value: 559,
                weight: 459,
            },
            {
                group: '130',
                value: 1118,
                weight: 918,
            },
            {
                group: '131',
                value: 1677,
                weight: 1377,
            },
            {
                group: '132',
                value: 955,
                weight: 855,
            },
            {
                group: '133',
                value: 1910,
                weight: 1710,
            },
            {
                group: '134',
                value: 3820,
                weight: 3420,
            },
            {
                group: '135',
                value: 955,
                weight: 855,
            },
            {
                group: '136',
                value: 237,
                weight: 137,
            },
            {
                group: '137',
                value: 474,
                weight: 274,
            },
            {
                group: '138',
                value: 948,
                weight: 548,
            },
            {
                group: '139',
                value: 711,
                weight: 411,
            },
            {
                group: '140',
                value: 906,
                weight: 806,
            },
            {
                group: '141',
                value: 1812,
                weight: 1612,
            },
            {
                group: '142',
                value: 1812,
                weight: 1612,
            },
            {
                group: '143',
                value: 324,
                weight: 224,
            },
            {
                group: '144',
                value: 648,
                weight: 448,
            },
            {
                group: '145',
                value: 648,
                weight: 448,
            },
            {
                group: '146',
                value: 730,
                weight: 630,
            },
            {
                group: '147',
                value: 1460,
                weight: 1260,
            },
            {
                group: '148',
                value: 2920,
                weight: 2520,
            },
            {
                group: '149',
                value: 2190,
                weight: 1890,
            },
            {
                group: '150',
                value: 115,
                weight: 15,
            },
            {
                group: '151',
                value: 230,
                weight: 30,
            },
            {
                group: '152',
                value: 230,
                weight: 30,
            },
            {
                group: '153',
                value: 590,
                weight: 490,
            },
            {
                group: '154',
                value: 1180,
                weight: 980,
            },
            {
                group: '155',
                value: 1180,
                weight: 980,
            },
            {
                group: '156',
                value: 574,
                weight: 474,
            },
            {
                group: '157',
                value: 1148,
                weight: 948,
            },
            {
                group: '158',
                value: 2296,
                weight: 1896,
            },
            {
                group: '159',
                value: 574,
                weight: 474,
            },
            {
                group: '160',
                value: 697,
                weight: 597,
            },
            {
                group: '161',
                value: 1394,
                weight: 1194,
            },
            {
                group: '162',
                value: 2091,
                weight: 1791,
            },
            {
                group: '163',
                value: 751,
                weight: 651,
            },
            {
                group: '164',
                value: 751,
                weight: 651,
            },
            {
                group: '165',
                value: 612,
                weight: 512,
            },
            {
                group: '166',
                value: 612,
                weight: 512,
            },
            {
                group: '167',
                value: 1034,
                weight: 934,
            },
            {
                group: '168',
                value: 2068,
                weight: 1868,
            },
            {
                group: '169',
                value: 1034,
                weight: 934,
            },
            {
                group: '170',
                value: 140,
                weight: 40,
            },
            {
                group: '171',
                value: 280,
                weight: 80,
            },
            {
                group: '172',
                value: 866,
                weight: 766,
            },
            {
                group: '173',
                value: 1732,
                weight: 1532,
            },
            {
                group: '174',
                value: 3464,
                weight: 3064,
            },
            {
                group: '175',
                value: 866,
                weight: 766,
            },
            {
                group: '176',
                value: 708,
                weight: 608,
            },
            {
                group: '177',
                value: 1416,
                weight: 1216,
            },
            {
                group: '178',
                value: 708,
                weight: 608,
            },
            {
                group: '179',
                value: 685,
                weight: 585,
            },
            {
                group: '180',
                value: 652,
                weight: 552,
            },
            {
                group: '181',
                value: 521,
                weight: 421,
            },
            {
                group: '182',
                value: 1042,
                weight: 842,
            },
            {
                group: '183',
                value: 521,
                weight: 421,
            },
            {
                group: '184',
                value: 582,
                weight: 482,
            },
            {
                group: '185',
                value: 626,
                weight: 526,
            },
            {
                group: '186',
                value: 1252,
                weight: 1052,
            },
            {
                group: '187',
                value: 1252,
                weight: 1052,
            },
            {
                group: '188',
                value: 1072,
                weight: 972,
            },
            {
                group: '189',
                value: 2144,
                weight: 1944,
            },
            {
                group: '190',
                value: 154,
                weight: 54,
            },
            {
                group: '191',
                value: 154,
                weight: 54,
            },
            {
                group: '192',
                value: 347,
                weight: 247,
            },
            {
                group: '193',
                value: 694,
                weight: 494,
            },
            {
                group: '194',
                value: 1388,
                weight: 988,
            },
            {
                group: '195',
                value: 694,
                weight: 494,
            },
            {
                group: '196',
                value: 555,
                weight: 455,
            },
            {
                group: '197',
                value: 1110,
                weight: 910,
            },
            {
                group: '198',
                value: 2220,
                weight: 1820,
            },
            {
                group: '199',
                value: 1087,
                weight: 987,
            },
            {
                group: '200',
                value: 2174,
                weight: 1974,
            },
        ],
        capacity: 90870,
    },
];
